services:
    heritage_api:
        container_name: heritage_api
        build:
            context: ./api
            dockerfile: ./docker/Dockerfile
        ports:
          - 8080:8080
        networks:
          - backend

    web_server:
        container_name: heritage_server
        build:
            context: ./react
            dockerfile: ./docker/Dockerfile
        restart: unless-stopped
        depends_on:
            - heritage_api
        ports:
            - 80:80
            - 443:443
            - 443:443/udp
        volumes:
            - ./server:/etc/caddy
            - caddy_data:/data
            - caddy_config:/config
        networks:
            - backend

volumes:
    caddy_data:
    caddy_config:

networks:
    backend:
