name: Automatic deployment on VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    name: Push images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/adbc-0/heritage_spa:{{ github.sha }}
